KEWA DOCTOR Django website/PotatoLeafDisease/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('classifierApp.urls', namespace='potatoleafdisease')),
    path('api-auth/', include('rest_framework.urls')),
]

KEWA DOCTOR Django website/classifierApp/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static 
from django.conf import settings

from .views import PotatoAPIView

app_name = 'classifierApp'

urlpatterns = [
    path('', views.home, name='homepage'),
    path('history', views.history, name='historypage'),


    path('predict', views.predictImage),
    path('viewdb', views.viewDataBase, name='view'),

    # path('register', views.register, name='register'),
    
    # path('login/', views.loginUser, name="login"),
    # path('changepw/', views.changePW, name="changepw"),
    # path('logout/', views.logoutUser, name="logout"),  

    path('indexm', views.indexm, name='indexmpage'),

    path('api/routes', views.getRoutes),
    path('api/results/all', PotatoAPIView.as_view()),
    path('api/predict', PotatoAPIView.as_view(), name='predict'),


]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

KEWA DOCTOR Django website/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'img/favicon.ico' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <title>KEWA DOCTOR</title>
    <style >
		iframe,
		video{
			display:block;
			margin:1em auto;
			width:80%;
			height: calc(.4625 * 80vw);
			max-width:  637px;
			min-width:  420px;

		}
	</style>
</head>

<body>
    <!-- Header -->
    <section id="header">
        <div class="header container">
            <div class="nav-bar">
                <div class="brand">
                    <a href="/">
                        <img src="{% static 'img/logo.png' %}" id="logo" style="width: 75px; height: 75px;" alt="img">
                    </a>
                </div>
                <div class="nav-list">
                    <div class="hamburger">
                        <div class="bar"></div>
                    </div>
                    <ul>
                        <li><a href="/" data-after="Home">Home</a></li>
                        <li><a href="history" data-after="View History">View History</a></li>
                        <li><a href="#projects" data-after="Disease">Disease</a></li>
                        <li><a href="#about" data-after="About">About</a></li>
                        <li><a href="#contact" data-after="Contact">Contact</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </section>
    <!-- End Header -->
    {% block content%} {% endblock %}




    <!-- Projects Section -->
    <section id="projects">
        <div class="projects container">
            <div class="projects-header">
                <h1 class="section-title">Disease<span>Types</span></h1>
            </div>
            <h1>Early<span>Blight<span></h1><p></p><p></p>
      <div class="project-item">
        <div class="project-info">
          <div class="project-img">
            <img src="{% static 'img/2.jpg' %}" alt="img">
          </div><p></p><p></p>
          <h2>What is Late Blight?</h2><p></p>
          <p><b>Late Blight </b> is caused by the funguslike oomycete pathogen Phytophthora infestans. This potentially devastating disease can infect potato foliage and tubers at any stage of crop development. <br><br></p>
          <p></p>
        </div>
      </div><p></p><p> </p><p></p><p></p>
      <h1>Late<span>Blight</h1><p></p><p></p>
      <div class="project-item">
        <div class="project-info">
          <div class="project-img">
            <img src="{% static 'img/3.jpg' %}" alt="img">
          </div><p></p><p></p>
          <h2>What is Early Blight?</h2><p></p>
          <p><b>Early Blight </b>is caused by the fungus Alternaria solani. It is found wherever potatoes are grown.<br></p>
          <p></p>
        </div>
      </div>
    </div>
  </section>
  <!-- End Projects Section -->

  <!-- About Section -->
  <section id="about">
    <div class="about container">
      <div class="col-left">
        <div class="about-img">
          <img src="{% static 'img/1.jpg' %}" alt="img">
        </div>
      </div>
      <div class="col-right">
        <h1 class="section-title">About <span>us</span></h1>
            <h2>KEWA DOCTOR</h2>
            <p>Your assistant to treat potato leaf diseases.</p>
            <p>A project that was aimed to classify the disease of a potato leaf, suggests the treatment for a leaf disease. </p>
            <p>Check our API at <a href="https://rapidapi.com/Ugyenwangdi/api/kewa-doctor/" target="_blank"><b style="color: blue;">RapidAPI Hub</a></b>
            </p>

        </div>
        </div>
    </section>
    <!-- End About Section -->
    <section>
		<!-- video controls>
			<source src="123.mp4" type="video/mp4">
		</video> -->
		<iframe src="https://drive.google.com/file/d/12O5pnJhVD8CvH88mZKWMXgG3hqLDgX5B/preview" width="640" height="480" allow="autoplay ; encrypted-media" allowfullscreen></iframe>
	</section>
    <!-- Contact Section -->
    <section id="contact">
        <div class="contact container">
            <div>
                <h1 class="section-title">Contact <span>info</span></h1>
            </div>
            <div class="contact-items">
                <div class="contact-item">
                    <div class="icon"><img src="https://img.icons8.com/bubbles/100/000000/phone.png" /></div>
                    <div class="contact-info">
                        <h1>Phone</h1>
                        <h2>+975 12345678</h2>

                        {% comment %} <h2>+975 77714393</h2>
                        <h2>+975 77887853</h2>
                        <h2>+975 77354374</h2>
                        <h2>+975 17743174</h2> {% endcomment %}
                    </div>
                </div>
                <div class="contact-item">
                    <div class="icon"><img src="https://img.icons8.com/bubbles/100/000000/new-post.png" /></div>
                    <div class="contact-info">
                        <h1>Email</h1>
                        {% comment %} <h2>kewadoctor@gmail.com</h2> {% endcomment %}

                        <h2>12190051.gcit@rub.edu.bt</h2>
                        <h2>12190053.gcit@rub.edu.bt</h2>
                        <h2>12190093.gcit@rub.edu.bt</h2>
                        <h2>12190105.gcit@rub.edu.bt</h2> 

                    </div>
                </div>
                <div class="contact-item">
                    <div class="icon"><img src="https://img.icons8.com/bubbles/100/000000/map-marker.png" /></div>
                    <div class="contact-info">
                        <h1>Address</h1>
                        <h2>Mongar, Gyalpozhing, Bhutan</h2>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- End Contact Section -->

    <!-- Footer -->
    <section id="footer">
        <div class="footer container">
            <div class="brand">
                <h1><span>Potato Leaf</span> Disease Classification</h1>
            </div>
            <h2>Solution For Your Potato Plant Diseases</h2>
            <div class="social-icon">
                <div class="social-item">
                    <a href="https://www.facebook.com" target="_blank"><img src="https://img.icons8.com/bubbles/100/000000/facebook-new.png" /></a>
                </div>
                <div class="social-item">
                    <a href="https://www.instagram.com/" target="_blank"><img src="https://img.icons8.com/bubbles/100/000000/instagram-new.png" /></a>
                </div>
                <div class="social-item">
                    <a href="https://gitlab.com/p7521/potatoleafdisease" target='_blank'><img src="https://img.icons8.com/color/48/undefined/gitlab.png"/></a>
                  </div>
                <!-- <div class="social-item">
                    <a href="https://twitter.com" target="_blank"><img src="https://img.icons8.com/bubbles/100/000000/twitter.png" /></a>
                </div> -->

                {% comment %} <div class="social-item">

                    <a href="mailto:kewadoctor@gmail.com"><img src="https://img.icons8.com/carbon-copy/100/000000/apple-mail.png" /></a>

                </div> {% endcomment %}


            </div>
            <p>© 2022 KEWADOCTOR. All rights reserved</p>
        </div>
    </section>
    <!-- End Footer -->
    <script src="{% static 'js/app.js' %}"></script>
</body>

</html>

KEWA DOCTOR Django website/templates/change_password.html
{% load static %}


<!DOCTYPE html>
<html>

<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>Change password</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'img/favicon.ico' %}">

    <style>
        .login--wrapper {
            display: flex;
            align-items: center;
            height: 80vh;
            justify-content: center;
        }
        
        .form {
            width: 500px;
        }
    </style>
</head>

<body>
    <div class="container">

        <div class="login--wrapper">
            <form method='POST' class="form">
                {% csrf_token %}
                <h3>Create a new password</h3>
                {% if error %}
                <p>{{error}}</p>
                {% endif %}
                <p></p>
                <div class="mb-3">
                    <label for="nameinput" class="form-label">Username</label>
                    <input type="text" class="form-control" name="username" id="nameinput" aria-describedby="emailHelp">
                </div>
                <div class="mb-3">
                    <label for="Password1" class="form-label">New Password</label>
                    <input type="password" class="form-control" name="password1" id="Password1">
                </div>

                <div class="mb-3">
                    <label for="Password2" class="form-label">Confirm Password</label>
                    <input type="password" class="form-control" name="password2" id="Password2">
                </div>

                <button type="submit" class="btn btn-dark btn-sm">Update</button>
                <p><a href="{% url 'classifierApp:login' %}">Login?</a> </p>
                <p><a href="{% url 'classifierApp:homepage' %}">Home</a> </p>

            </form>

        </div>

    </div>
</body>

</html>

KEWA DOCTOR Django website/templates/headerPage.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

    <title>PLDC</title>

    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="author" content="Tooplate">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <link rel="shortcut icon" type="image/x-icon" href="{% static 'img/favicon.ico' %}">

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">

    <!-- MAIN CSS -->

</head>

<body id="top" data-spy="scroll" data-target=".navbar-collapse" data-offset="50" style="margin: 5rem;">


    <div style="align-items: center;">

        <div class="container">
            <!-- MENU -->
            <header>
                <section class="navbar navbar-default navbar-static-top" role="navigation" style="align-items: center;">
                    <div class="container ">

                        <div class="navbar-header " style="margin-bottom: 8px;">
                            <button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                             <span class="icon icon-bar"></span>
                             <span class="icon icon-bar"></span>
                             <span class="icon icon-bar"></span>
                            </button>

                            <!-- lOGO TEXT HERE -->
                            <a href="/" class="navbar-brand "><i class="fa fa-h-square"></i>Potato Leaf Disease Classification</a>
                        </div>

                        <!-- MENU LINKS -->
                        <div class="collapse navbar-collapse">
                            <ul class="nav navbar-nav navbar-right">
                                <li><a href="/" class="smoothScroll">Home</a></li>
                                <li><a href="viewdb" class="smoothScroll">View gallery</a></li>
                            </ul>
                        </div>

                    </div>
                </section>
            </header>
        </div>


        <!-- HOME -->


        <div class="container">
            {% block content%} {% endblock %}

        </div>

    </div>





    <!-- SCRIPTS -->
    <script src="{% static 'js/jquery.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jquery.sticky.js' %}"></script>
    <script src="{% static 'js/jquery.stellar.min.js' %}"></script>
    <script src="{% static 'js/wow.min.js' %}"></script>
    <script src="{% static 'js/smoothscroll.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/custom.js' %}"></script>

</body>

</html>

KEWA DOCTOR Django website/templates/history.html
{% extends 'base.html' %} {% block content%}

<section id="projects">
    <div class="projects container">
        <div class="projects-header">
            <h1 class="section-title"><span>History</span></h1>
        </div>
        <div class="all-projects">
            <div class="project-item">
                <div class="project-img">
                    <img src={{src}} alt="img">
                </div>
                <div class="project-info">

                    <p>Image: {{image}}</p><br><br>
                    <p>Predicted: {{predicted}}</p>
                    <p>Image Link: {{imagelink}}</p>
                    {% comment %} <p>Confidence: {{confidence}}</p> {% endcomment %}
                    <p>Saved: {{saved}}</p><br> {% if lateblight %}
                    <p>
                        <!-- <b>Late Blight </b><br> Blight is caused by the funguslike oomycete pathogen Phytophthora infestans. This potentially devastating disease can infect potato foliage and tubers at any stage of crop development. --><br><b>Treatment:</b>
                        <br>Late Blight is controlled by eliminating cull piles and volunteer potatoes, using proper harvesting and storage practices, and applying fungicides when necessary. Air drainage to facilitate the drying of foliage each day is
                        important.
                    </p>

                    {% elif earlyblight %}
                    <p>
                        <b>Early Blight </b><br> Early Blight is caused by the fungus Alternaria solani. It is found wherever potatoes are grown.<br><br>Treatment <br> 1. planting potato varieties that are resistant to the disease; late maturing are more
                        resistant than early maturing varieties.<br> 2. Avoid overhead irrigation and allow for sufficient aeration between plants to allow the foliage to dry as quickly as possible.<br> 3. Keep the potato plants healthy and stress free
                        by providing adequate nutrition and sufficient irrigation, especially later in the growing season after flowering when plants are most susceptible to the disease.</p><br><br><br> {% elif healthy %}
                    <p>The leaf was a healythy Leaf</p><br><br><br> {% else %}
                    <p>The image was predicted Unknoen</p><br><br><br> {% endif %}
                </div>
            </div>
        </div>
    </div>

    {% endblock %}

    <!-- </section>
<section id="upload" style="background-color: gray;">

    <div class="banner">
        <div style="text-align: center;">

            <div style="padding: 9rem;">

                <p>History</p>
                <p>Image: {{image}}</p>
                <p>Predicted: {{predicted}}</p>
                <p>Image link: {{imagelink}}</p>

                <p>Confidence: {{confidence}}</p>
                <p>Saved: {{saved}}</p>
                <img src={{src}} style="width: 100px; height: 100px;"><br><br><br> {% if lateblight %}

                <p>
                    <b>Late Blight </b><br> Blight is caused by the funguslike oomycete pathogen Phytophthora infestans. This potentially devastating disease can infect potato foliage and tubers at any stage of crop development. <br><br>Treatment : <br>late
                    Blight is controlled by eliminating cull piles and volunteer potatoes, using proper harvesting and storage practices, and applying fungicideswhen necessary. Air drainage to facilitate the drying of foliage each day is important.
                </p>

                {% elif earlyblight %}


                <p>
                    <b>Early Blight </b><br> Early Blight is caused by the fungus Alternaria solani. It is found wherever potatoes are grown.<br> Treatment 1. planting potato varieties that are resistant to the disease; late maturing are more resistant
                    than early maturing varieties.<br> 2. Avoid overhead irrigation and allow for sufficient aeration between plants to allow the foliage to dry as quickly as possible.<br> 3. Keep the potato plants healthy and stress free by providing
                    adequate nutrition and sufficient irrigation, especially later in the growing season after flowering when plants are most susceptible to the disease.
                </p>

                {% elif healthy %}
                <p>The Leaf was a Healthy leaf</p>

                {% else %}
                <p>The image was predicted Unknown</p>
                {% endif %}


                <p></p>
            </div>

        </div>


    </div>


</section> -->

KEWA DOCTOR Django website/templates/index.html
{% extends 'base.html' %} {% block content%} {% if predictedLabel %}

<section id="projects1">
    <div class="projects container1">
        <div class="projects-header1">
            <h1 class="section-title"><span>Result</span></h1>
        </div>
        <div class="all-projects1">
            <div class="project-item1">
                <div class="project-img1">
                    <img src={{filePathName}} alt="img">
                </div>
                <div class="project-info1">
                    <p>The predicted class is {{predictedLabel}}</p>
                    {% comment %} <p>Confidence: {{confidence}}%</p> {% endcomment %}
                    <p>Image name: {{filename}}</p>
                    {% if lateblight %}
                    <p><br><b>Treatment:</b>
                        <br>Late Blight is controlled by eliminating cull piles and volunteer potatoes, using proper harvesting and storage practices, and applying fungicides when necessary. Air drainage to facilitate the drying of foliage each day is
                        important.
                    </p>



                    {% elif earlyblight %}

                    <p>
                        <b>Early Blight </b><br> Early Blight is caused by the fungus Alternaria solani. It is found wherever potatoes are grown.<br><br> Treatment <br> 1. planting potato varieties that are resistant to the disease; late maturing are
                        more resistant than early maturing varieties.<br> 2. Avoid overhead irrigation and allow for sufficient aeration between plants to allow the foliage to dry as quickly as possible.<br> 3. Keep the potato plants healthy and stress
                        free by providing adequate nutrition and sufficient irrigation, especially later in the growing season after flowering when plants are most susceptible to the disease.</p><br><br><br> {% elif healthy %}
                    <p>The leaf was a healthy Leaf</p><br><br><br> {% else %}
                    <p>The image was predicted Unknown</p><br><br><br> {% endif %}
                </div><br><br><br>

                <p style="color: white;">Predict<a href="/" style="color: white;"> again?</a></p>
            </div>
        </div>
    </div>
</section>
<!-- 
<section style="background-color: gray; text-align: center;">

    <div style="padding: 9rem;">
        <div>
            <h3>Result</h3>
            <p>The predicted class is {{predictedLabel}}</p>
            <p>Confidence: {{confidence}}%</p>
            <img src={{filePathName}} alt="image" style="width: 500px;">
            <p>Image: {{filename}}</p>



        </div>

        <div>
            {% if lateblight %}

            <p>
                <b>Late Blight </b><br>Late Blight is caused by the funguslike oomycete pathogen Phytophthora infestans. This potentially devastating disease can infect potato foliage and tubers at any stage of crop development. <br><br>Treatment : <br>late
                Blight is controlled by eliminating cull piles and volunteer potatoes, using proper harvesting and storage practices, and applying fungicideswhen necessary. Air drainage to facilitate the drying of foliage each day is important.
            </p>
            {% elif earlyblight %}


            <p>
                <b>Early Blight </b><br> Early Blight is caused by the fungus Alternaria solani. It is found wherever potatoes are grown.<br> Treatment 1. planting potato varieties that are resistant to the disease; late maturing are more resistant than
                early maturing varieties.<br> 2. Avoid overhead irrigation and allow for sufficient aeration between plants to allow the foliage to dry as quickly as possible.<br> 3. Keep the potato plants healthy and stress free by providing adequate
                nutrition and sufficient irrigation, especially later in the growing season after flowering when plants are most susceptible to the disease.
            </p>
            {% elif healthy %}
            <p>The Leaf was a Healthy leaf</p>

            {% else %}
            <p>The image was predicted Unknown</p>
            {% endif %}

            <p>Predict</p><a href="/"> again?</a>

        </div>



    </div>

</section> -->



{% else %}

<section id="upload" style="background-color: gray;">
    <div class="banner">
        <div class="info">



            <h1>UPLOAD IMAGE <span>FOR CLASSIFICATION</span></h1>
            <div class="whole" style="width:40.4%">
                <div class="wrapper">
                    <div class="image">
                        <img id="chooseimg" src="" alt="">
                    </div>
                    <div class="content">
                        <div class="icon">
                            <i class="fas fa-cloud-upload-alt"></i>
                        </div>
                        <div class="text">
                            No image chosen, yet!
                        </div>
                    </div>
                    <div id="cancel-btn">
                        <i class="fas fa-times"></i>
                    </div>
                </div>
                <!-- <button onclick="defaultBtnActive()" id="custom-btn">Select Image</button>
              <input id="default-btn" type="file" hidden>
              <button onclick="" id="custom-btn">Predict</button>
              <input id="default-btn" type="file" hidden> -->


                <form method="post" enctype="multipart/form-data" action="predict">

                    {% csrf_token %}
                    <span onclick="defaultBtnActive()" id="custom-btn" style="text-align: center; padding: 1.3rem;"><input id="default-btn" name="filePath" type="file" hidden>Select</span>



                    <input type="submit" id="custom-btn" value="Submit"></input>
                </form>


            </div>
        </div>

</section>

{% endif %} {% endblock %}

KEWA DOCTOR Django website/templates/indexm.html
{% extends 'headerPage.html' %} {% block content%}

<div style="align-items: center;">
    <h4>Upload Image for Classification</h4>


    <br>

    <form method="post" enctype="multipart/form-data" action="predict">

        {% csrf_token %}
        <div class="col-md-4 col-sm-4"><label for="fname">Upload Image File Here:</label> </div> <input name="filePath" type="file"><br><br>
        <br>


        <input type="submit" value="Submit">
    </form>


</div>
<div style="padding: 8rem; display: grid; align-items: center; ">
    {% if predictedLabel %}
    <h4>The predicted class is {{predictedLabel}}</h4>
    <p>Confidence: {{confidence}}%</p>
    <img src={{filePathName}} alt="image">
    <p style="padding: 8px;">{{filename}}</p> {% endif %}
</div>






</form>

</div>


<br> {% endblock %}

KEWA DOCTOR Django website/templates/login.html
{% load static %}


<!DOCTYPE html>
<html>

<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>Login</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'img/favicon.ico' %}">

    <style>
        .login--wrapper {
            display: flex;
            align-items: center;
            height: 80vh;
            justify-content: center;
        }
        
        .form {
            width: 500px;
        }
    </style>
</head>

<body>
    <div class="container">

        <div class="login--wrapper">
            <form method='POST' class="form">
                {% csrf_token %}
                <h3>Welcome, Please Login </h3>
                {% if error %}
                <p>{{error}}</p>
                {% endif %}
                <p></p>
                <div class="mb-3">
                    <label for="inputname" class="form-label">Username</label>
                    <input type="text" class="form-control" name="username" id="inputname">
                </div>
                <div class="mb-3">
                    <label for="passwordinput" class="form-label">Password</label>
                    <input type="password" class="form-control" name="password" id="passwordinput">
                </div>

                <button type="submit" class="btn btn-dark btn-sm">Enter</button>

                <p>Change password <a href="{% url 'classifierApp:changepw' %}">Here</a> </p>
                <p>Go to <a href="{% url 'classifierApp:homepage' %}">Home</a> </p>


            </form>

        </div>

    </div>
</body>

</html>

KEWA DOCTOR Django website/templates/register.html
 {% load static %}


<!DOCTYPE html>
<html>

<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>Change password</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'img/favicon.ico' %}">

    <style>
        .login--wrapper {
            display: flex;
            align-items: center;
            height: 80vh;
            justify-content: center;
        }
        
        .form {
            width: 500px;
        }
    </style>
</head>

<body>
    <div class="container">

        <div class="login--wrapper">
            <form method='POST' class="form">
                {% csrf_token %}
                <h2 class="section-title">Register</h2>
                {% for message in messages %}
                <h3>{{ message }}</h3>
                {% endfor %}
                <p></p>

                <div class="mb-3">
                    <label for="nameinput" class="form-label">Username</label>
                    <input type="text" name="username" class="form-control" id="nameinput">
                </div>

                <div class="mb-3">
                    <label for="email" class="form-label">Email</label>
                    <input type="text" class="form-control" name="email" id="email">
                </div>

                <div class="mb-3">
                    <label for="Password1" class="form-label">Password</label>
                    <input type="password" class="form-control" name="password1" id="Password1">
                </div>

                <div class="mb-3">
                    <label for="Password2" class="form-label">Confirm Password</label>
                    <input type="password" class="form-control" name="password2" id="Password2">
                </div>

                <button type="submit" class="btn btn-dark btn-sm">Register</button><br>
                <p><a href="{% url 'classifierApp:login' %}">Login?</a> </p>
                <p><a href="{% url 'classifierApp:homepage' %}">Home</a> </p>




            </form>

        </div>

    </div>
</body>

</html>

KEWA DOCTOR Django website/templates/viewDB.html
{% extends 'headerPage.html' %} {% block content%}

<div style="display: block; align-content: center;">

    {% for i in all_results %}
    <p>Predicted {{i.image}} as: {{i.predicted}}</p>
    <p>Imagelink {{i.imagelink}}</p>
    <p>Confidence {{i.confidence}}%</p>
    <p>{{i.saved}}</p>

    <img src={{i.imagepath}} style="width: 100px;"><br><br><br> {% endfor%} {% endblock %}
</div>